#!/usr/bin/env bash
# configures on nginx server so that /redirect_me redirects to another page
# redirection configured as "301 Moved Permanently"


sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
