#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for file in *; # * displays files in CWD
do
	filename=${file#*-} # removes everything after first dash
	echo "$filename" # displays the editted file name
done
