#!/usr/bin/env bash
# A Bash script that gives you information about the school file
if [ -e "school" ] # -e checks for file existence. -e for existence
then
	echo "school file exists"

	if [ -s "school" ] #checks if not empty. -s for size
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
