#!/usr/bin/env bash
# Install the ufw firewall and set up rules on server 1

sudo apt-get -y update
sudo apt-get -y upgrade

# enable ufw
sudo ufw enable
# check status
sudo ufw status verbose
# set the rules(default)
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allow port 22(ssh) 443(https ssl) 80(http)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# check status
sudo ufw status verbose
